// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6PrR9i316w4QUNrwdkSXMq6pv6H6NBL0',
    appId: '1:828312872083:android:d7bcd73c380faf8806d966',
    messagingSenderId: '828312872083',
    projectId: 'gymhibrido-9d221',
    storageBucket: 'gymhibrido-9d221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbK_QfhdgQpoyiJWDu9vSRUfeJ0ji3IJw',
    appId: '1:828312872083:ios:6aff923c911e0d3b06d966',
    messagingSenderId: '828312872083',
    projectId: 'gymhibrido-9d221',
    storageBucket: 'gymhibrido-9d221.firebasestorage.app',
    iosBundleId: 'com.example.appGymHibrido',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ubv5hB-scNn66Bjg4UhSLdpZhhC_LpE',
    appId: '1:828312872083:web:3c751c6f15a715f106d966',
    messagingSenderId: '828312872083',
    projectId: 'gymhibrido-9d221',
    authDomain: 'gymhibrido-9d221.firebaseapp.com',
    storageBucket: 'gymhibrido-9d221.firebasestorage.app',
    measurementId: 'G-VFL9DTRXD0',
  );

}